# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
        sharedev.requests: '0.25'
        sharedev.limits: '1.0'
        sharedev.memory: '0.2'
        sharedev.vendor: 'example.com'
        sharedev.model: 'mydev'
    spec:
      schedulerName: scheduler-plugins-scheduler
      containers:
      - name: device
        image: docker.io/zbsss/benchmark:latest
        imagePullPolicy: Always
