apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-manager-daemon
spec:
  selector:
    matchLabels:
      app: device-manager
  template:
    metadata:
      labels:
        app: device-manager
    spec:
      serviceAccountName: evict-pods-sa
      containers:
      - name: device-manager
        image: docker.io/zbsss/device-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          hostPort: 50051
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evict-pods-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evict-pods-role
rules:
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evict-pods-rolebinding
subjects:
- kind: ServiceAccount
  name: evict-pods-sa
  namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: evict-pods-role

