apiVersion: v1
kind: Pod
metadata:
  name: device
  labels:
    sharedev.requests: '0.5'
    sharedev.limit: '1.0'
    sharedev.device: 'example.com-mydev'
spec:
  restartPolicy: Never
  containers:
  - name: device
    image: docker.io/zbsss/device:latest
    imagePullPolicy: Always
    env:
    - name: CLIENT_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: DEVICE_ID
      value: "dev-1"
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

