apiVersion: v1
kind: Pod
metadata:
  name: device-plugin-test
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000"
    resources:
      limits:
        example.com/mydev: 1
