apiVersion: v1
kind: Pod
metadata:
  name: device
  labels:
        sharedev.requests: '0.25'
        sharedev.limits: '1.0'
        sharedev.memory: '0.25'
        sharedev.vendor: 'example.com'
        sharedev.model: 'mydev'
spec:
  schedulerName: scheduler-plugins-scheduler
  restartPolicy: Never
  containers:
  - name: device
    image: docker.io/zbsss/device:latest
    imagePullPolicy: Always

