apiVersion: v1
kind: Service
metadata:
  name: device-manager-service
spec:
  selector:
    app: device-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-manager
  template:
    metadata:
      labels:
        app: device-manager
    spec:
      containers:
      - name: device-manager
        image: docker.io/zbsss/device-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
