apiVersion: v1
kind: Pod
metadata:
  name: device
spec:
  containers:
  - name: device
    image: docker.io/zbsss/device:latest
    imagePullPolicy: Always
    env:
    - name: CLIENT_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: DEVICE_ID
      value: "dev-1"
    - name: DEVICE_MANAGER_SERVICE_ADDR
      value: "device-manager-service:80"
